### ISSUE TITLE
npm install waterlock-local-auth

### ISSUE THREAD

**Issue by GeoCloud** [waterlock/waterlock-local-auth#27]
Hello,
We have an issue with the installation on Maverick and we have nodejs 0.12.

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "waterlock-local-auth"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

**Comment by wayne-o** [comment]
I installed from npm yesterday using 0.12 without issue. Although bcrypt make no promises for 0.12: https://www.npmjs.com/package/bcrypt

"node-gyp only works with stable/released versions of node. Since the bcrypt module uses node-gyp to build and install you'll need a stable version of node to use bcrypt"

Could you try reverting to an older node and see if that eliminates the issue else I will try and repro my end and see if there is anything I can help with.

**Comment by GeoCloud** [comment]
It's very strange in installation of waterlock-local-auth, the package.son calls bcrypt@0.7.8. Is it possible to call the last version of bcrypt ?

gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "waterlock-local-auth" "-g"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.

**Comment by leejt489** [comment]
I am also seeing this error after updating to node 0.12.1

**Comment by AlexanderFillbrunn** [comment]
I have the same problem on MacOS 10.10 with node 0.12.1. Is there any workaround?
